name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "ruadmin" -Password (ConvertTo-SecureString -AsPlainText "frank" -Force)
    - run: git clone https://github.com/sarthakroy2002/Windows10Debloater.git C:\Users\runneradmin\Windows10Debloater
    - run: cd C:\Users\runneradmin\Windows10Debloater
    - name: Debloat step 1
      run: C:\Users\runneradmin\Windows10Debloater\Windows10SysPrepDebloater.ps1 -Debloat 
      shell: powershell
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
